version: '2'
services:
   build:
      build: boxfuse-sample-java-war-hello-custom
      environment:
        - TYPO3_CONTEXT=Development/Docker
   tomcat:
      build: tomcat
      links:
         - build
      ports:
         - "8080:8080"
      volumes_from:
         - build