version: '3.7'
services:
   tomcat:
      build:
        context: ./tomcat
        args:
           - project_path=https://github.com/boxfuse/boxfuse-sample-java-war-hello
      ports:
         - "8080:8080"